version: '2'
services:
  cachepix:
    build: .
    image: philcollins/cachepix
    environment:
      - PCACHE_REBUILD=true
    volumes:
      - .:/go/src/github.com/ssalevan/cachepix
    privileged: true
    ports:
      - "12345:12345"
